Repository LingmoOS/LingmoUI, pull requests merged in 2025-02, with the labels that each got.

#30 feat: add new components and update MainPage
  example/CMakeLists.txt
  example/qml/global/SidebarItems.qml
  example/qml/main.qml
  example/qml/pages/Buttons.qml
  example/qml/pages/TabView.qml
  example/qml/windows/MainPage.qml
  example/qml/windows/MainWindow.qml
  src/Controls/LingmoBadge.qml
  src/Controls/LingmoControl.qml
  src/Controls/LingmoDivider.qml
  src/Controls/LingmoInfoBar.qml
  src/Controls/LingmoNavigationView.qml
  src/Controls/LingmoPage.qml
  src/Controls/LingmoPanelItem.qml
  src/Controls/LingmoPanelItemEmpty.qml
  src/Controls/LingmoPanelItemExpander.qml
  src/Controls/LingmoPanelItemHeader.qml
  src/Controls/LingmoPanelItemSeparator.qml
  src/Controls/LingmoProgressButton.qml
  src/Controls/LingmoScrollablePage.qml
  src/Controls/LingmoTabView.qml
  src/LingmoDefines.h
Labels: enhancement, 🚀 merge it!

#31 feat: add python package build workflow
  .github/workflows/build.yml
  CMakeLists.txt
  Compatible/CMakeLists.txt
  Compatible/lingmoui.cpp
  setup.py
  src/CMakeLists.txt
Labels: enhancement, 🚀 merge it!

#34 fix: improve blur and round corner effects
  src/Controls/LingmoAcrylic.qml
  src/Controls/LingmoNavigationView.qml
  src/Controls/LingmoWindow.qml
  src/LingmoTools.cpp
Labels: enhancement, 🚀 merge it!

#36 bump(setup.py): change python package version
  setup.py
Labels: 🚀 merge it!

#38 feat(LingmoTabView): add some functions
  example/qml/pages/TabView.qml
  setup.py
  src/Controls/LingmoTabView.qml
Labels: documentation, enhancement, 🚀 merge it!

#37 docs: add changelog
  CHANGELOG.md
  README.md
Labels: documentation, 🚀 merge it!

#39 feat(LingmoTabView): add function for switching to tab
  example/qml/pages/TabView.qml
  setup.py
  src/Controls/LingmoTabView.qml
Labels: enhancement, 🚀 merge it!

#41 fix: Add Qt6 SVG plugin dependency, optimize setup.py, remove redundant logs, upgrade Python version to 3.9
  .cmake/CheckForQtVersion/CMakeLists.txt
  .github/workflows/build.yml
  debian/control
  pyproject.toml
  setup.py
  src/Controls/LingmoNavigationView.qml
Labels: 🚀 merge it!

#47 fix(Hotkey): fix pointer issue and callback
  example/qml/main.qml
  example/qml/windows/ShortcutWindow.qml
  src/LingmoHotkey.cpp
Labels: bug, 🚀 merge it!

#50 chore(build): fix build options and dependency
  CMakeLists.txt
  debian/control
  example/qml/main.qml
Labels: 🚀 merge it!

#51 chore: release 3.1.0
  .gitignore
  CHANGELOG.md
  Doxyfile
  debian/changelog
  setup.py
Labels: documentation, 🚀 merge it!
